### ISSUE TITLE
ERROR! Unexpected Exception, this is probably a bug: 'file'

### ISSUE THREAD

**Issue by mckila** [f5devcentral/ansible-role-f5ansible#2]
##  Summary
when attempting to run test playbook from role 

```
ansible-playbook -vvv -i inventory/ep/f5/test/hosts bigip_device_facts_gal_role.yml --limit "my_f5_hosti"
```

using following APB

```
- hosts: localhost
  connection: local

  roles:
    - role: f5devcentral.f5ansible

  tasks:

    - name: Create virtual server
      bigip_virtual_server:
        name: test_virtual_server
        destination: 2.1.3.4
        port: 9000
        description: My description
        snat: Automap
        pool: pool1
        provider:
          user: admin
          server: bigip01.test
          password: secret
          validate_certs: no
      register: result
```

### ANSIBLE VERSION

```
ansible-playbook 2.7.5
  config file = /ansible/ansible.cfg
  configured module search path = [u'/ansible/library/modules']
  ansible python module location = /usr/local/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible-playbook
  python version = 2.7.15 (default, Oct 16 2018, 07:58:03) [GCC 6.3.0 20170516]
```

### OS/ ENVIRONMENT
```
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=debian
```

### RESULTS
```
ERROR! Unexpected Exception, this is probably a bug: 'file'
the full traceback was:

Traceback (most recent call last):
  File "/usr/local/bin/ansible-playbook", line 118, in <module>
    exit_code = cli.run()
  File "/usr/local/lib/python2.7/site-packages/ansible/cli/playbook.py", line 122, in run
    results = pbex.run()
  File "/usr/local/lib/python2.7/site-packages/ansible/executor/playbook_executor.py", line 81, in run
    pb = Playbook.load(playbook_path, variable_manager=self._variable_manager, loader=self._loader)
  File "/usr/local/lib/python2.7/site-packages/ansible/playbook/__init__.py", line 54, in load
    pb._load_playbook_data(file_name=file_name, variable_manager=variable_manager)
  File "/usr/local/lib/python2.7/site-packages/ansible/playbook/__init__.py", line 106, in _load_playbook_data
    entry_obj = Play.load(entry, variable_manager=variable_manager, loader=self._loader, vars=vars)
  File "/usr/local/lib/python2.7/site-packages/ansible/playbook/play.py", line 112, in load
    return p.load_data(data, variable_manager=variable_manager, loader=loader)
  File "/usr/local/lib/python2.7/site-packages/ansible/playbook/base.py", line 230, in load_data
    self._attributes[target_name] = method(name, ds[name])
  File "/usr/local/lib/python2.7/site-packages/ansible/playbook/play.py", line 197, in _load_roles
    roles.append(Role.load(ri, play=self))
  File "/usr/local/lib/python2.7/site-packages/ansible/playbook/role/__init__.py", line 161, in load
    r._load_role_data(role_include, parent_role=parent_role)
  File "/usr/local/lib/python2.7/site-packages/ansible/playbook/role/__init__.py", line 228, in _load_role_data
    self._task_blocks = load_list_of_blocks(task_data, play=self._play, role=self, loader=self._loader, variable_manager=self._variable_manager)
  File "/usr/local/lib/python2.7/site-packages/ansible/playbook/helpers.py", line 80, in load_list_of_blocks
    loader=loader,
  File "/usr/local/lib/python2.7/site-packages/ansible/playbook/block.py", line 93, in load
    return b.load_data(data, variable_manager=variable_manager, loader=loader)
  File "/usr/local/lib/python2.7/site-packages/ansible/playbook/base.py", line 230, in load_data
    self._attributes[target_name] = method(name, ds[name])
  File "/usr/local/lib/python2.7/site-packages/ansible/playbook/block.py", line 129, in _load_block
    use_handlers=self._use_handlers,
  File "/usr/local/lib/python2.7/site-packages/ansible/playbook/helpers.py", line 147, in load_list_of_tasks
    loader=loader
  File "/usr/local/lib/python2.7/site-packages/ansible/playbook/task_include.py", line 70, in load
    task.args['_raw_params'] = task.args.pop('file')
```

**Comment by wojtek0806** [comment]
can you try changing to actually reference your host definition in the `hosts` file `inventory/ep/f5/test/hosts`:

`hosts: localhost`  <- change

**Comment by wojtek0806** [comment]
@mckila can you try updating the role and see if the issue persists?

**Comment by mckila** [comment]
Yes that fixed this issue.  - Thank You!
