### ISSUE TITLE
Unexpected failure during module execution

### ISSUE THREAD

**Issue by mckila** [f5devcentral/ansible-role-f5ansible#5]
Using ansible version:

```root@9587684da40c:/ansible# ansible-playbook --version
ansible-playbook 2.7.5
  config file = /ansible/ansible.cfg
  configured module search path = [u'/ansible/library/modules']
  ansible python module location = /usr/local/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible-playbook
  python version = 2.7.15 (default, Oct 16 2018, 07:58:03) [GCC 6.3.0 20170516]
```
OS/Environment:

```PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

using the following APB:

```---
#!/bin/usr/env ansible-playbook -vv
- name: bigip_create_qkview.yml
  hosts: bigips
  connection: local

  roles:
     - role: f5devcentral.f5ansible


  tasks:


    - name: Fetch a qkview from the remote device
      bigip_qkview:
        asm_request_log: yes
        complete_information: yes
        exclude:
          - audit
          - secure
        dest: /tmp/bigip_hostname.qkview
        provider:
          password: 'secret'
          server: 'bigip_hostname'
          user: admin
          validate_certs: no
#      delegate_to: localhost
```

RESULTS:

```The full traceback is:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 140, in run
    res = self._execute()
  File "/usr/local/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 563, in _execute
    self._handler = self._get_action_handler(connection=self._connection, templar=templar)
  File "/usr/local/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 929, in _get_action_handler
    shared_loader_obj=self._shared_loader_obj,
  File "/usr/local/lib/python2.7/site-packages/ansible/plugins/loader.py", line 378, in get
    self._module_cache[path] = self._load_module_source(name, path)
  File "/usr/local/lib/python2.7/site-packages/ansible/plugins/loader.py", line 357, in _load_module_source
    module = imp.load_source(full_name, path, module_file)
  File "/ansible/f5devcentral.f5ansible/action_plugins/bigip.py", line 30, in <module>
    from ansible.plugins.action.network import ActionModule as ActionNetworkModule
ImportError: No module named network

fatal: [bigip_hostname1]: FAILED! => {
    "msg": "Unexpected failure during module execution.",
    "stdout": ""
}
The full traceback is:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 140, in run
    res = self._execute()
  File "/usr/local/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 563, in _execute
    self._handler = self._get_action_handler(connection=self._connection, templar=templar)
  File "/usr/local/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 929, in _get_action_handler
    shared_loader_obj=self._shared_loader_obj,
  File "/usr/local/lib/python2.7/site-packages/ansible/plugins/loader.py", line 378, in get
    self._module_cache[path] = self._load_module_source(name, path)
  File "/usr/local/lib/python2.7/site-packages/ansible/plugins/loader.py", line 357, in _load_module_source
    module = imp.load_source(full_name, path, module_file)
  File "/ansible/f5devcentral.f5ansible/action_plugins/bigip.py", line 30, in <module>
    from ansible.plugins.action.network import ActionModule as ActionNetworkModule
ImportError: No module named network

fatal: [bigip_hostname2]: FAILED! => {
    "msg": "Unexpected failure during module execution.",
    "stdout": ""
}```

**Comment by wojtek0806** [comment]
try removing and reinstalling the role this issue should have been resolved with the fix last week

**Comment by mckila** [comment]
hmm no luck  however i noticed this when i attempted to reinstall 

```
root@9587684da40c:/ansible# ansible-galaxy remove --roles-path ./roles/ f5devcentral.bigip_to_ansible
- successfully removed f5devcentral.bigip_to_ansible
root@9587684da40c:/ansible# ansible-galaxy install --roles-path ./roles/ f5devcentral.bigip_to_ansible
- downloading role 'bigip_to_ansible', owned by f5devcentral
- downloading role from https://github.com/f5devcentral/ansible-role-bigip_to_ansible/archive/master.tar.gz
- extracting f5devcentral.bigip_to_ansible to /ansible/roles/f5devcentral.bigip_to_ansible
- f5devcentral.bigip_to_ansible (master) was installed successfully
 [WARNING]: - dependency f5devcentral.f5ansible from role f5devcentral.bigip_to_ansible differs from already installed version
(v2018.12.20), skipping
```

yet i do not see where else that role could be installed

**Comment by mckila** [comment]
same error:
```
The full traceback is:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 140, in run
    res = self._execute()
  File "/usr/local/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 563, in _execute
    self._handler = self._get_action_handler(connection=self._connection, templar=templar)
  File "/usr/local/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 929, in _get_action_handler
    shared_loader_obj=self._shared_loader_obj,
  File "/usr/local/lib/python2.7/site-packages/ansible/plugins/loader.py", line 378, in get
    self._module_cache[path] = self._load_module_source(name, path)
  File "/usr/local/lib/python2.7/site-packages/ansible/plugins/loader.py", line 357, in _load_module_source
    module = imp.load_source(full_name, path, module_file)
  File "/ansible/roles/f5devcentral.f5ansible/action_plugins/bigip.py", line 30, in <module>
    from ansible.plugins.action.network import ActionModule as ActionNetworkModule
ImportError: No module named network

fatal: [bigip_hostname1]: FAILED! => {
    "msg": "Unexpected failure during module execution.",
    "stdout": ""
}
The full traceback is:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 140, in run
    res = self._execute()
  File "/usr/local/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 563, in _execute
    self._handler = self._get_action_handler(connection=self._connection, templar=templar)
  File "/usr/local/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 929, in _get_action_handler
    shared_loader_obj=self._shared_loader_obj,
  File "/usr/local/lib/python2.7/site-packages/ansible/plugins/loader.py", line 378, in get
    self._module_cache[path] = self._load_module_source(name, path)
  File "/usr/local/lib/python2.7/site-packages/ansible/plugins/loader.py", line 357, in _load_module_source
    module = imp.load_source(full_name, path, module_file)
  File "/ansible/roles/f5devcentral.f5ansible/action_plugins/bigip.py", line 30, in <module>
    from ansible.plugins.action.network import ActionModule as ActionNetworkModule
ImportError: No module named network

fatal: [bigip_hostname2]: FAILED! => {
    "msg": "Unexpected failure during module execution.",
    "stdout": ""
}

**Comment by wojtek0806** [comment]
Can you check if you have got network.py in this folder:

`/ansible/roles/f5devcentral.f5ansible/action_plugins/`

Also check `/ansible/roles/f5devcentral.f5ansible/action_plugins/bigip.py` if it has these lines:

```
try:
    from library.plugins.action.network import ActionModule as ActionNetworkModule
except Exception:
    try:
        from action_plugins.network import ActionModule as ActionNetworkModule
    except Exception:
        from ansible.plugins.action.network import ActionModule as ActionNetworkModule
```

**Comment by wojtek0806** [comment]
i reverted the change that started all this, should be good now, just download latest tagged release :)
